name: 'Install NPM Dependencies'
description: 'Install NPM Dependencies'

inputs:
  cache-key:
    description: 'Cache key'
    required: true
  cache-restore-keys:
    description: 'Cache restore keys'
    required: true
outputs:
  cache-hit:
    description: 'Whether or not the cache was hit'
    value: ${{ steps.npm-cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - run: mkdir ~/.npm-cache
      shell: sh
      name: Create NPM cache directory
    - name: Load NPM cache
      id: npm-cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.npm-cache
          node_modules
        key: ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.cache-restore-keys }}
    - name: Install NPM dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci --prefer-offline --no-audit
      shell: sh
    - name: Rebuild dependencies
      run: npm rebuild
      shell: sh
    - name: Save NPM cache
      if: steps.npm-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: ${{ inputs.cache-key }}
        path: |
          ~/.npm-cache
          node_modules
