name: Ubuntu + Windows

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-windows-node
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/shared-tests.yml
    secrets: inherit
    with:
      experimental: true
      os: windows-latest
      runtime: node
      # as string for inputs workaround not accepting arrays
      versions: '[20, 21, 22, 23, 24]'